import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AlertCircle, ArrowUpRight, CalendarDays, CheckCircle2, ChevronDown, Code2, FileImage, ImagePlus, Layers3, LoaderCircle, Mail, Phone, RefreshCw, Rocket, Send, Sparkles, UploadCloud, UserRound, X } from 'lucide-react';

const initialForm={fullName:'',email:'',phone:'',projectTitle:'',category:'',submissionDate:'',projectUrl:'',techStack:'',description:''};
const categories=['Web Application','Mobile App','UI/UX Design','AI / Machine Learning','Other'];
function validate(form,file){const errors={};if(form.fullName.trim().length<2)errors.fullName='Enter your full name using at least 2 characters.';if(!/^\S+@\S+\.\S+$/.test(form.email.trim()))errors.email='Enter a valid email such as name@example.com.';if(!/^\+?[0-9][0-9\s-]{7,16}$/.test(form.phone.trim()))errors.phone='Enter a valid phone number with 8 to 17 digits.';if(form.projectTitle.trim().length<3)errors.projectTitle='Use at least 3 characters for the project title.';if(!categories.includes(form.category))errors.category='Choose your project category.';if(!form.submissionDate)errors.submissionDate='Select the project submission date.';else if(new Date(`${form.submissionDate}T00:00:00`)>new Date())errors.submissionDate='Submission date cannot be in the future.';try{const url=new URL(form.projectUrl);if(!['http:','https:'].includes(url.protocol))throw new Error()}catch{errors.projectUrl='Enter a complete link beginning with http:// or https://.'}if(form.techStack.trim().length<2)errors.techStack='List at least one technology used.';if(form.description.trim().length<30)errors.description='Write at least 30 characters about your project.';if(!file)errors.coverImage='Choose a project image before submitting.';else if(!['image/jpeg','image/png','image/webp'].includes(file.type))errors.coverImage='Choose a JPG, PNG, or WebP image.';else if(file.size>3*1024*1024)errors.coverImage='Image must be smaller than 3 MB.';return errors}
function FieldError({children}){return children?<small className="field-error"><AlertCircle size={12}/>{children}</small>:null}
export default function App(){
 const[form,setForm]=useState(initialForm),[file,setFile]=useState(null),[preview,setPreview]=useState(''),[errors,setErrors]=useState({}),[submitting,setSubmitting]=useState(false),[submissions,setSubmissions]=useState([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[toast,setToast]=useState(null);const fileInput=useRef(null);const maxDate=useMemo(()=>new Date().toISOString().slice(0,10),[]);
 const loadSubmissions=useCallback(async()=>{setLoading(true);setLoadError('');try{const response=await fetch('/api/submissions'),data=await response.json();if(!response.ok)throw new Error(data.message);setSubmissions(data)}catch(error){setLoadError(error.message||'Could not load submissions.')}finally{setLoading(false)}},[]);
 useEffect(()=>{loadSubmissions()},[loadSubmissions]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(null),4200);return()=>clearTimeout(timer)},[toast]);
 function update(event){const{name,value}=event.target;setForm(current=>({...current,[name]:value}));setErrors(current=>({...current,[name]:''}))}
 function chooseFile(event){const selected=event.target.files?.[0]||null;if(preview)URL.revokeObjectURL(preview);setFile(selected);setPreview(selected&&selected.type.startsWith('image/')?URL.createObjectURL(selected):'');setErrors(current=>({...current,coverImage:''}))}
 function clearFile(){if(preview)URL.revokeObjectURL(preview);setPreview('');setFile(null);if(fileInput.current)fileInput.current.value=''}
 async function submit(event){event.preventDefault();const nextErrors=validate(form,file);setErrors(nextErrors);if(Object.keys(nextErrors).length){setToast({type:'error',text:'Please correct the highlighted fields.'});setTimeout(()=>document.querySelector('.field-error')?.closest('label, .upload-field')?.scrollIntoView({behavior:'smooth',block:'center'}),0);return}setSubmitting(true);try{const body=new FormData();Object.entries(form).forEach(([key,value])=>body.append(key,value));body.append('coverImage',file);const response=await fetch('/api/submissions',{method:'POST',body}),data=await response.json();if(!response.ok){const error=new Error(data.message);error.fields=data.errors;throw error}setSubmissions(current=>[data.submission,...current]);setForm(initialForm);clearFile();setErrors({});setToast({type:'success',text:'Project submitted successfully. Your entry is now live.'})}catch(error){if(error.fields)setErrors(error.fields);setToast({type:'error',text:error.message||'Submission failed. Please try again.'})}finally{setSubmitting(false)}}
 return <div className="app-shell"><header className="topbar"><a href="#top" className="brand"><span><Rocket size={19}/></span>launchform</a><div className="header-meta"><span><i/> API connected</span><a href="#submissions">View submissions <ArrowUpRight size={15}/></a></div></header><main id="top">
  <section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={13}/> Week 3 · Form engineering</span><h1>Show the work<br/><em>you’re proud of.</em></h1><p>A professional project submission portal with real validation, secure image uploads, and immediate feedback at every step.</p><div className="hero-points"><span><CheckCircle2 size={15}/> Dual-layer validation</span><span><CheckCircle2 size={15}/> Secure file handling</span><span><CheckCircle2 size={15}/> Real API persistence</span></div></div><div className="hero-card"><div className="hero-card-top"><Layers3 size={20}/><span>Submission readiness</span><strong>9 fields</strong></div><div className="readiness"><i/><i/><i/></div><div className="hero-stats"><div><strong>{submissions.length}</strong><span>Projects received</span></div><div><strong>3 MB</strong><span>Secure upload limit</span></div><div><strong>2×</strong><span>Validation layers</span></div></div></div></section>
  <section className="content-grid"><form className="submission-form" onSubmit={submit} noValidate>
   <SectionHead number="01" title="Creator details" text="Tell us who is behind this project." required/><div className="form-grid three"><InputField label="Full name" name="fullName" value={form.fullName} onChange={update} icon={UserRound} placeholder="e.g. Amir Latif" error={errors.fullName} disabled={submitting}/><InputField label="Email address" name="email" type="email" value={form.email} onChange={update} icon={Mail} placeholder="name@example.com" error={errors.email} disabled={submitting}/><InputField label="Phone number" name="phone" value={form.phone} onChange={update} icon={Phone} placeholder="+92 300 1234567" error={errors.phone} disabled={submitting}/></div><div className="form-divider"/>
   <SectionHead number="02" title="Project information" text="Share the essentials reviewers need."/><div className="form-grid two"><InputField label="Project title" name="projectTitle" value={form.projectTitle} onChange={update} icon={Code2} placeholder="Your project name" error={errors.projectTitle} disabled={submitting}/><label><span>Category</span><div className="input-wrap select"><Layers3 size={17}/><select name="category" value={form.category} onChange={update} disabled={submitting}><option value="">Select a category</option>{categories.map(category=><option key={category}>{category}</option>)}</select><ChevronDown size={16}/></div><FieldError>{errors.category}</FieldError></label><InputField label="Submission date" name="submissionDate" type="date" max={maxDate} value={form.submissionDate} onChange={update} icon={CalendarDays} error={errors.submissionDate} disabled={submitting}/><InputField label="Live or GitHub URL" name="projectUrl" type="url" value={form.projectUrl} onChange={update} icon={ArrowUpRight} placeholder="https://github.com/..." error={errors.projectUrl} disabled={submitting}/><InputField className="full" label="Technology stack" name="techStack" value={form.techStack} onChange={update} icon={Code2} placeholder="React, Express, Node.js, CSS" error={errors.techStack} disabled={submitting}/><label className="full"><span>Project description <b>{form.description.length}/600</b></span><textarea name="description" value={form.description} onChange={update} placeholder="Explain the problem, your solution, and what makes the project valuable..." maxLength="600" disabled={submitting}/><FieldError>{errors.description}</FieldError></label></div><div className="form-divider"/>
   <SectionHead number="03" title="Project cover" text="Add one strong image that represents your work."/><div className={`upload-field ${errors.coverImage?'has-error':''}`}><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseFile} disabled={submitting}/>{preview?<div className="image-preview"><img src={preview} alt="Selected project preview"/><div><FileImage size={20}/><strong>{file.name}</strong><span>{(file.size/1024/1024).toFixed(2)} MB · Ready to upload</span></div><button type="button" onClick={clearFile} aria-label="Remove image"><X size={18}/></button></div>:<button type="button" className="upload-prompt" onClick={()=>fileInput.current?.click()} disabled={submitting}><span><UploadCloud size={24}/></span><strong>Drop your project image here</strong><small>or click to browse · JPG, PNG, WebP · Maximum 3 MB</small></button>}<FieldError>{errors.coverImage}</FieldError></div>
   <div className="submit-row"><div><CheckCircle2 size={16}/><span>Validated securely on the frontend and backend.</span></div><button className="submit-button" disabled={submitting}>{submitting?<><LoaderCircle className="spin" size={18}/> Submitting project...</>:<><Send size={17}/> Submit project</>}</button></div>
  </form></section>
  <section id="submissions" className="submissions-section"><div className="gallery-heading"><div><span className="eyebrow">Submission gallery</span><h2>Projects ready for review</h2><p>Every entry below was validated and saved by the backend.</p></div><span className="gallery-count">{submissions.length} {submissions.length===1?'submission':'submissions'}</span></div>{loading?<GalleryState icon={LoaderCircle} spin title="Loading submissions..."/>:loadError?<GalleryState icon={AlertCircle} title="Could not load projects" text={loadError} retry={loadSubmissions}/>:submissions.length?<div className="project-grid">{submissions.map(item=><article key={item.id} className="project-card"><div className="card-image"><img src={item.imageUrl} alt={`${item.projectTitle} cover`}/><span>{item.category}</span></div><div className="card-body"><div className="card-meta"><span>{new Date(`${item.submissionDate}T00:00:00`).toLocaleDateString('en',{month:'short',day:'numeric',year:'numeric'})}</span><span>{item.fullName}</span></div><h3>{item.projectTitle}</h3><p>{item.description}</p><div className="card-footer"><span>{item.techStack}</span><a href={item.projectUrl} target="_blank" rel="noreferrer"><ArrowUpRight size={17}/></a></div></div></article>)}</div>:<GalleryState icon={ImagePlus} title="No projects submitted yet" text="Your first valid submission will appear here."/>}</section>
 </main><footer><a className="brand" href="#top"><span><Rocket size={17}/></span>launchform</a><p>Built with React + Express · Real forms, real validation, real feedback.</p></footer>{toast&&<div className={`toast ${toast.type}`} role="status">{toast.type==='success'?<CheckCircle2 size={19}/>:<AlertCircle size={19}/>}<span>{toast.text}</span><button onClick={()=>setToast(null)} aria-label="Dismiss"><X size={17}/></button></div>}</div>
}
function SectionHead({number,title,text,required}){return <div className="section-heading"><div><span className="step">{number}</span><div><h2>{title}</h2><p>{text}</p></div></div>{required&&<span>All fields required</span>}</div>}
function InputField({label,icon:Icon,error,className='',...props}){return <label className={className}><span>{label}</span><div className="input-wrap"><Icon size={17}/><input {...props}/></div><FieldError>{error}</FieldError></label>}
function GalleryState({icon:Icon,title,text,retry,spin}){return <div className="gallery-state"><span className="empty-icon"><Icon className={spin?'spin':''} size={25}/></span><strong>{title}</strong>{text&&<p>{text}</p>}{retry&&<button onClick={retry}><RefreshCw size={15}/> Try again</button>}</div>}