import { AlertCircle, ArrowUpRight, CalendarDays, CheckCircle2, ChevronDown, Code2, FileImage, Layers3, LoaderCircle, Mail, Phone, Send, UploadCloud, UserRound, X } from 'lucide-react';
import { useFormState } from '../context/FormContext';
import { categories } from '../validation';
function FieldError({children}){return children?<small className="field-error"><AlertCircle size={12}/>{children}</small>:null}
function SectionHead({number,title,text,required}){return <div className="section-heading"><div><span className="step">{number}</span><div><h2>{title}</h2><p>{text}</p></div></div>{required&&<span>All fields required</span>}</div>}
function InputField({label,icon:Icon,error,className='',...props}){return <label className={className}><span>{label}</span><div className="input-wrap"><Icon size={17}/><input {...props}/></div><FieldError>{error}</FieldError></label>}
export default function SubmissionForm(){const{form,file,preview,errors,submitting,fileInput,maxDate,update,chooseFile,clearFile,submit}=useFormState();return <section className="content-grid"><form className="submission-form" onSubmit={submit} noValidate>
 <SectionHead number="01" title="Creator details" text="Tell us who is behind this project." required/><div className="form-grid three"><InputField label="Full name" name="fullName" value={form.fullName} onChange={update} icon={UserRound} placeholder="e.g. Amir Latif" error={errors.fullName} disabled={submitting}/><InputField label="Email address" name="email" type="email" value={form.email} onChange={update} icon={Mail} placeholder="name@example.com" error={errors.email} disabled={submitting}/><InputField label="Phone number" name="phone" value={form.phone} onChange={update} icon={Phone} placeholder="+92 300 1234567" error={errors.phone} disabled={submitting}/></div><div className="form-divider"/>
 <SectionHead number="02" title="Project information" text="Share the essentials reviewers need."/><div className="form-grid two"><InputField label="Project title" name="projectTitle" value={form.projectTitle} onChange={update} icon={Code2} placeholder="Your project name" error={errors.projectTitle} disabled={submitting}/><label><span>Category</span><div className="input-wrap select"><Layers3 size={17}/><select name="category" value={form.category} onChange={update} disabled={submitting}><option value="">Select a category</option>{categories.map(category=><option key={category}>{category}</option>)}</select><ChevronDown size={16}/></div><FieldError>{errors.category}</FieldError></label><InputField label="Submission date" name="submissionDate" type="date" max={maxDate} value={form.submissionDate} onChange={update} icon={CalendarDays} error={errors.submissionDate} disabled={submitting}/><InputField label="Live or GitHub URL" name="projectUrl" type="url" value={form.projectUrl} onChange={update} icon={ArrowUpRight} placeholder="https://github.com/..." error={errors.projectUrl} disabled={submitting}/><InputField className="full" label="Technology stack" name="techStack" value={form.techStack} onChange={update} icon={Code2} placeholder="React, Express, Node.js, CSS" error={errors.techStack} disabled={submitting}/><label className="full"><span>Project description <b>{form.description.length}/600</b></span><textarea name="description" value={form.description} onChange={update} placeholder="Explain the problem, your solution, and what makes the project valuable..." maxLength="600" disabled={submitting}/><FieldError>{errors.description}</FieldError></label></div><div className="form-divider"/>
 <SectionHead number="03" title="Project cover" text="Add one strong image that represents your work."/><div className={`upload-field ${errors.coverImage?'has-error':''}`}><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseFile} disabled={submitting}/>{preview?<div className="image-preview"><img src={preview} alt="Selected project preview"/><div><FileImage size={20}/><strong>{file.name}</strong><span>{(file.size/1024/1024).toFixed(2)} MB · Ready to upload</span></div><button type="button" onClick={clearFile} aria-label="Remove image"><X size={18}/></button></div>:<button type="button" className="upload-prompt" onClick={()=>fileInput.current?.click()} disabled={submitting}><span><UploadCloud size={24}/></span><strong>Drop your project image here</strong><small>or click to browse · JPG, PNG, WebP · Maximum 3 MB</small></button>}<FieldError>{errors.coverImage}</FieldError></div>
 <div className="submit-row"><div><CheckCircle2 size={16}/><span>Global form state is validated on the frontend and backend.</span></div><button className="submit-button" disabled={submitting}>{submitting?<><LoaderCircle className="spin" size={18}/> Submitting project...</>:<><Send size={17}/> Submit project</>}</button></div>
 </form></section>}