import { useState } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, Check, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck, Sparkles, UserRound } from 'lucide-react';
import { useAuth } from './AuthContext';

export default function AuthPage({ mode }) {
  const isSignup = mode === 'signup'; const { user, login, signup } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [form, setForm] = useState({ name: '', email: '', password: '' }); const [errors, setErrors] = useState({}); const [message, setMessage] = useState(location.state?.message || ''); const [busy, setBusy] = useState(false); const [showPassword, setShowPassword] = useState(false);
  if (user) return <Navigate to="/dashboard" replace />;
  function update(event) { setForm((current) => ({ ...current, [event.target.name]: event.target.value })); setErrors((current) => ({ ...current, [event.target.name]: '' })); setMessage(''); }
  function validate() { const next = {}; if (isSignup && form.name.trim().length < 2) next.name = 'Enter at least 2 characters.'; if (!/^\S+@\S+\.\S+$/.test(form.email.trim())) next.email = 'Enter a valid email address.'; if (!form.password) next.password = 'Password is required.'; else if (isSignup && (form.password.length < 8 || !/[A-Z]/.test(form.password) || !/[a-z]/.test(form.password) || !/\d/.test(form.password))) next.password = 'Use 8+ characters with uppercase, lowercase, and a number.'; setErrors(next); return !Object.keys(next).length; }
  async function submit(event) { event.preventDefault(); if (!validate()) return; setBusy(true); setMessage(''); try { if (isSignup) { await signup(form); navigate('/login', { replace: true, state: { message: 'Account created successfully. Sign in to continue.' } }); } else { await login({ email: form.email, password: form.password }); navigate(location.state?.from || '/dashboard', { replace: true }); } } catch (error) { setMessage(error.message); if (error.fields) setErrors(error.fields); } finally { setBusy(false); } }
  return <main className="auth-page">
    <section className="auth-showcase"><Link className="auth-brand" to="/"><span><Sparkles size={19}/></span>momentum</Link><div className="showcase-copy"><span className="auth-eyebrow">Secure productivity workspace</span><h1>Plan with clarity.<br/><em>Execute with confidence.</em></h1><p>Your priorities, progress, and personal workspace—protected by secure account authentication.</p><ul><li><Check size={16}/> Private, user-specific task workspace</li><li><Check size={16}/> Secure password hashing and sessions</li><li><Check size={16}/> Protected dashboard and API access</li></ul></div><div className="security-note"><ShieldCheck size={20}/><div><strong>Security by default</strong><span>Passwords are hashed. Session tokens stay in protected HTTP-only cookies.</span></div></div></section>
    <section className="auth-panel"><div className="auth-card"><div className="auth-heading"><span>{isSignup ? 'Create your workspace' : 'Welcome back'}</span><h2>{isSignup ? 'Start building momentum' : 'Sign in to Momentum'}</h2><p>{isSignup ? 'Create a secure account in less than a minute.' : 'Enter your account details to access your dashboard.'}</p></div>{message && <div className={location.state?.message ? 'auth-message success' : 'auth-message'} role="alert">{message}</div>}<form onSubmit={submit} noValidate autoComplete="off">
      {isSignup && <label><span>Full name</span><div className="auth-input"><UserRound size={18}/><input name="name" value={form.name} onChange={update} placeholder="Your name" autoComplete="off" disabled={busy}/></div>{errors.name && <small>{errors.name}</small>}</label>}
      <label><span>Email address</span><div className="auth-input"><Mail size={18}/><input type="email" name="email" value={form.email} onChange={update} placeholder="you@example.com" autoComplete="off" disabled={busy}/></div>{errors.email && <small>{errors.email}</small>}</label>
      <label><span>Password</span><div className="auth-input"><LockKeyhole size={18}/><input type={showPassword ? 'text' : 'password'} name="password" value={form.password} onChange={update} placeholder={isSignup ? '8+ secure characters' : 'Enter your password'} autoComplete="new-password" disabled={busy}/><button type="button" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff size={18}/> : <Eye size={18}/>}</button></div>{errors.password && <small>{errors.password}</small>}{isSignup && !errors.password && <small className="hint">Use uppercase, lowercase, and at least one number.</small>}</label>
      <button className="auth-submit" disabled={busy}>{busy ? 'Please wait...' : isSignup ? 'Create secure account' : 'Sign in to dashboard'}{!busy && <ArrowRight size={18}/>}</button>
    </form><p className="auth-switch">{isSignup ? 'Already have an account?' : 'New to Momentum?'} <Link to={isSignup ? '/login' : '/signup'}>{isSignup ? 'Sign in' : 'Create an account'}</Link></p></div></section>
  </main>;
}